config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #neighborhoods
  get '/neighborhoods' => 'neighborhoods#index'
  get '/neighborhoods/new' => 'neighborhoods#new'
  post '/neighborhoods' => 'neighborhoods#create'
  get '/neighborhoods/:id' => 'neighborhoods#show', as: "neighborhood"

  #bodegas
  get '/bodegas' => 'bodegas#index'
  get '/bodegas/new' => 'bodegas#new'
  post '/bodegas' => 'bodegas#create'
  get '/bodegas/:id' => 'bodegas#show', as: 'bodega'
  get '/bodegas/:id/edit' => 'bodegas#edit'
  put '/bodegas/:id' => 'bodegas#update'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bodega.rb
class Bodega < ApplicationRecord
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bodegas_controller.rb
class BodegasController < ApplicationController

  def index
    @bodegas = Bodega.all
  end

  def show
    @bodega = Bodega.find(params[:id])
    @neighborhood = Neighborhood.find_by(name: @bodega.neighborhood)
  end

  def new
  end

  def create
    @bodega = Bodega.create(name: params[:name], rating: params[:rating], neighborhood: params[:neighborhood], comments: params[:comments])
    redirect_to bodega_path(@bodega)
  end

  def edit
    @bodega = Bodega.find(params[:id])
  end

  def update
    @bodega = Bodega.find(params[:id])
    @bodega.update(name: params[:name], rating: params[:rating], neighborhood: params[:neighborhood], comments: params[:comments])
    redirect_to bodega_path(@bodega)
  end

end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController

  def index
    @neighborhoods = Neighborhood.all
  end

  def show
    @neighborhood = Neighborhood.find(params[:id])
    @bodegas = Bodega.all
  end

  def new
  end

  def create
    @neighborhood = Neighborhood.create(name: params[:name], city: params[:city])
    redirect_to neighborhood_path(@neighborhood)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bodegas/edit.html.erb
<h3>Edit this bodega:</h3>

<%= form_tag bodega_path(@bodega), method: "PUT" do %>
  <label>Name:</label><br>
  <%= text_field_tag :name, @bodega.name %><br>

  <label>Rating:</label><br>
  <%= text_field_tag :rating, @bodega.rating %><br>

  <label>Neighborhood:</label><br>
  <%= text_field_tag :neighborhood, @bodega.neighborhood %><br>

  <label>Comments:</label><br>
  <%= text_field_tag :comments, @bodega.comments %><br>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Submit">
<% end %>

app/views/bodegas/index.html.erb
<h1>My Favorite Bodega</h1>

<% @bodegas.each do |bodega| %>
  <p><%= link_to bodega.name, bodega_path(bodega) %></p>
<%end%>
<h3><%= link_to "Create New Favorite Bodega", '/bodegas/new'%></h3>
<p><%= link_to "Neighborhoods Home", neighborhoods_path %></p>

app/views/bodegas/new.html.erb
<h3>Create New Favorite Bodega:</h3>

<%= form_tag bodegas_path do %>
  <label>Name:</label><br>
  <%= text_field_tag :name %><br>

  <label>Rating:</label><br>
  <%= text_field_tag :rating %><br>

  <label>Neighborhood:</label><br>
  <%= text_field_tag :neighborhood %><br>

  <label>Comments:</label><br>
  <%= text_field_tag :comments %><br>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Submit">
<% end %>

app/views/bodegas/show.html.erb
<h1><%= @bodega.name %></h1>

<h3>Your rating: <%= @bodega.rating %>/10</h3>

<p>Neighborhood: <%= link_to @neighborhood.name, neighborhood_path(@neighborhood) %></p>

<p>Comments: <%= @bodega.comments %></p>

<h4><%= link_to "Edit", "/bodegas/#{@bodega.id}/edit" %></h4>

<p><%= link_to "Home", bodegas_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BodegaRaterApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/neighborhoods/index.html.erb
<h1>Choose Your Neighborhood</h1>
<% @neighborhoods.each do |neighborhood| %>

  <h3><%= link_to neighborhood.name, neighborhood_path(neighborhood) %></h3>

<%end%>
<h3><%= link_to "Create New Neighborhood", '/neighborhoods/new'%></h3>

<p><%= link_to "Bodega Home", bodegas_path %></p>

app/views/neighborhoods/new.html.erb
<h3>Create New Neighborhood:</h3>

<%= form_tag neighborhoods_path do %>
  <label>Name:</label><br>
  <%= text_field_tag :name %><br>

  <label>City:</label><br>
  <%= text_field_tag :city %><br>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Submit">
<% end %>

app/views/neighborhoods/show.html.erb
<h2><%= @neighborhood.name %></h2>

<% @bodegas.each do |bodega| %>
  <% if bodega.neighborhood == @neighborhood.name%>
    <p><%= link_to bodega.name, bodega_path(bodega) %></p>
  <%end%>
<% end %>

<h3><%= link_to "Home", neighborhoods_path %></h3>